### ISSUE TITLE
Generate Xcode projects

### ISSUE THREAD

**Issue by armcknight** [kimar/MMXcodeSample#2]
Love the project, it really helped me while developing for the board! 

I think the idea is to copy the entire contents of the repo for a new project? What if it were generated using [Xcodegen](https://github.com/yonaskolb/XcodeGen)?

I've used it a couple times now over the years, just recently using it at work to test our SDK's integration via cocoapods, carthage and SPM. I'd be happy to take a swing at the initial implementation based on what's currently in this repo.

**Comment by DK1DA** [comment]
Hey @armcknight, thanks for the kinds words. I love the idea of using Xcodegen for this, or Tust (https://tuist.io/docs/usage/get-started/), whatever makes more sense. I have used Xcodegen but not Tust yet, but I like the idea of writing the project definition in Swift as well. If you'd like to give any of those two a shot I'd be happy to review your PR.

**Comment by armcknight** [comment]
I have not tried Tuist, but had also viewed it with interest recently. Had forgotten, so thanks for reminding me. Doing it all in Swift is definitely a good way to go if the option is there! I will have a look at that this week.

**Comment by DK1DA** [comment]
Thank you! Looking forward to it. Let me know if you get stuck and I'll try to help.

**Comment by armcknight** [comment]
So after reading up on Tuist a little more closely, it seems too overarching of a tool for what I'm trying to do. I realized even an Xcodegen spec/generation would be too much, as all that's really needed is the SwiftIO package and your other project https://github.com/EmbeddedSwift/MadMachine. I think I'm going to focus on using that directly with just plain ol' Xcode projects 😄 

Thanks for your support and for your tools, hope I can help out in the future!
